### ISSUE TITLE
Plugin is not working with NX15

### ISSUE THREAD

**Issue by shilpimogha** [allenhwkim/ngentest#61]
Hi team, 
Is there any plan to upgrade the plugin to work with NX14 and NX15.

**Comment by allenhwkim** [comment]
Please provide a step to reproduce it. I am not using NX14 and NX15, but using Angular without it.
I will close this and  reopen this when a detail is provided.

Also version 1.5.0 is released
It removed Angular dependency by parsing code directly instead of using require-from-string https://github.com/allenhwkim/ngentest/pull/63

Please upgrade your command to 1.5.0, `npm install ngentest@1.5.0 -D`
